---
- name: Configure bond interface with Netplan
  hosts: all
  become: true
  gather_facts: yes

  vars:
    interfaces: ""
    bond_name: bond0
    bond_mode: 802.3ad
    bond_lacp_rate: fast
    bond_ip: ""
    bond_gateway: ""

  tasks:
    - name: Fail if server OS is not Ubuntu
      fail:
        msg: "This playbook is intended for Ubuntu only."
      when: ansible_distribution != 'Ubuntu'

    - name: Fail if missing variables
      fail:
        msg: Missing variables. Please provide variables by adding '-e "interfaces=if_name_1,if_name_2,if_name_n bond_ip=*.*.*.*/* bond_gateway=*.*.*.*"' to the command
      when: interfaces=="" or bond_ip=="" or bond_gateway==""
    
    - name: Ensure bonding kernel module is installed
      become: yes
      modprobe:
        name: bonding
        state: present

    - name: Configure bond
      template:
        src: templates/netplan-config.j2
        dest: /etc/netplan/01-bond-cfg.yaml
      notify: Apply Netplan Configuration

  handlers:
    - name: Apply Netplan Configuration
      shell: netplan apply