---
- name: Print Network Interface Information
  hosts: all
  gather_facts: yes

  tasks:
    - name: Fail if server OS is not Ubuntu
      fail:
        msg: "This playbook is intended for Ubuntu only."
      when: ansible_distribution != 'Ubuntu'

    - name: Get network interfaces
      shell: "ip -o link show | awk -F': ' '{print $2}'"
      register: network_interfaces

    - name: Get interface IP information
      shell: ip addr show | grep "inet " | awk "{print \$NF, \$3, \$2}"
      register: ip_information

    - name: Print interfaces
      debug:
        msg: "{{ network_interfaces.stdout_lines }}"

    - name: Print IP information
      debug:
        msg: "{{ ip_information.stdout_lines }}"
  